version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: travel-helper-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: travel_helper
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "65432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./prisma/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d travel_helper"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
